# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93d1135164bc8d21ef3d3f6aabdf736adba16dfc15b9f33938cb120334e709c68177c30d1314e0f08166079c93e1078d1a8967c7cd8ac1265703632db0c64071

test:
  secret_key_base: ad1ff84a35d7b0fbedab6424d726de231cf193c6b353ff6959291b124eefd639ea6099321805f43871261a7292d3d3ce2085888aa31e71add13acd2bbe0fc084

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
